# Generated by Django 3.2.3 on 2021-05-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.TextField(max_length=20)),
                ('emp_email', models.TextField(max_length=20)),
                ('emp_mobile', models.TextField(max_length=20)),
            ],
        ),
    ]
